datasets:
  electricity_file: "electricityConsumptionAndProductioction.csv"  # Replace with your actual electricity data filename
  weather_file: "dailyweatherdataRomania.csv"          # Replace with your actual weather data filename

training:
  date_column:
    electricity: "timestamp"                # Replace with the actual datetime column name in electricity data
    weather: "Date time"                   # Replace with the actual datetime column name in weather data
  columns:
    electricityConsumptionAndProductioction.csv:                  # Replace with your actual electricity file name
      - "Consumption"                      # Replace with the required columns for the electricity dataset
      - "Nuclear"
      - "Wind"
      - "Hydroelectric"
      - "Oil and Gas"
      # - "Coal"
      # - "Solar"
      # - "Biomass"
    dailyweatherdataRomania.csv:                      # Replace with your actual weather file name
      - "Temperature"                      # Replace with the required columns for the weather dataset
      - "Dew Point"
      - "Relative Humidity"
      - "Wind Speed"
      # - "Cloud Cover"
      # - "Visibility"
      # - "Sea Level Pressure"
  target_column: "Consumption"             # Replace with the target column name in electricity data
  sequence_length: 24                      # Sequence length for LSTM
  batch_size: 32                           # Batch size for DataLoader
  epochs: 10                               # Number of training epochs

model:
  lstm_units: 64                           # Number of LSTM units in the model
  learning_rate: 0.001                     # Learning rate for the optimizer
