datasets:
  inputs:
    - file: "inrusd.csv"
      datetime_column: "Date"
      columns:
        - "Close"
        -  "Open"
        - "High"
        - "Low"
        - "Volume"
        - "Adj Close"

      # - "Consumption"
      # - "Wind"
      # - "Hydroelectric"
      # - "Oil and Gas"

       
        # - 'close'
        # - "open"
        # - 'high'
        # - 'volume'
    - file: "gold.csv"
      datetime_column: "Date"
      columns:
        - "Gold Price"
        - "Open Gold price"
        - "High Price"
        - "Low Price"
        - "Gold Volume"
        - "Chg%"
        #---------------------
      # - "Maximum Temperature"
      # - "Dew Point"
      # - "Relative Humidity"
      # - "Wind Speed"
      # - "Cloud Cover"
      # - "Visibility"
      # - "Sea Level Pressure"
        #----------------
          # - "Open"
          # - "High"
          # - "Low"
          # - "Volume"
  target_column: "Close"
  target_dataset_index: 0 # Specify the index of the dataset containing the target column
  secondary_dataset_granularity: 'D' # Specify the granularity
splitting:
  steps_for_training: 2199   # Number of daily data points for training
  steps_for_prediction: 3   # N0umber of daily data points for prediction
training:
  sequence_length: 1
  batch_size: 24
  epochs: 10
  density_ratio_number: 1 #  
model:
  lstm_units: 64
  learning_rate: 0.001
  train_mode: "both"  # Specify which mode to use: "high_density_only", "low_density_only", or "both"
  test_mode: "low_density_only"
results:
  file: "results.yaml"
  output_predictions: "predictions.csv"
logging:
  level: INFO
  file: "training.log"